// Generated by CoffeeScript 1.6.3
(function() {
  exports.command = {
    name: 'look',
    aliases: ['l'],
    description: "Describes the environment around the player.",
    help: "Usage: look [direction or object]",
    action: function(context, request) {
      var direction, link, mob, room, _ref;
      mob = context.mob, room = context.room;
      mob.print("" + (room.get('title')));
      mob.print("" + (room.get('description')));
      mob.write(" exits: ");
      _ref = room.get('links');
      for (direction in _ref) {
        link = _ref[direction];
        mob.write("" + direction + " ");
      }
      return mob.print('');
    }
  };

}).call(this);
