// Generated by CoffeeScript 1.6.3
(function() {
  exports.command = {
    name: 'reload',
    aliases: [],
    description: "Reloads specified resource",
    help: "Usage: reload commands",
    action: function(context, request) {
      var args, mob, verb, world;
      mob = context.mob, world = context.world;
      verb = request.verb, args = request.args;
      if (args.length < 1) {
        mob.print("What do you want to reload?");
        return;
      }
      switch (args[0].toLowerCase()) {
        case 'commands':
          return world.commands.forEach(function(command) {
            console.log("Reloading command " + command.id);
            world.commands.loadFile(command.get('fileName'), true);
            return mob.print("Reloaded command " + command.id + ".");
          });
        default:
          return mob.print("Not a valid resource: " + args[0]);
      }
    }
  };

}).call(this);
