// Generated by CoffeeScript 1.6.3
(function() {
  var Area, AreaCollection, Collection, Model, RoomCollection, _ref, _ref1, _ref2,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('./'), Model = _ref.Model, Collection = _ref.Collection;

  RoomCollection = require('./room').RoomCollection;

  exports.Area = Area = (function(_super) {
    __extends(Area, _super);

    function Area() {
      _ref1 = Area.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Area.prototype.initialize = function() {
      return this.rooms = new RoomCollection();
    };

    return Area;

  })(Model);

  exports.AreaCollection = AreaCollection = (function(_super) {
    __extends(AreaCollection, _super);

    function AreaCollection() {
      _ref2 = AreaCollection.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    AreaCollection.prototype.model = Area;

    return AreaCollection;

  })(Collection);

}).call(this);
