// Generated by CoffeeScript 1.6.3
(function() {
  var Collection, Model, Room, RoomCollection, _ref, _ref1, _ref2,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('./'), Model = _ref.Model, Collection = _ref.Collection;

  exports.Room = Room = (function(_super) {
    __extends(Room, _super);

    function Room() {
      _ref1 = Room.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Room.prototype.getLocationId = function() {
      return "" + this.area.id + "#" + this.id;
    };

    Room.prototype.toString = function() {
      return "[Room " + (this.getLocationId()) + "]";
    };

    return Room;

  })(Model);

  exports.RoomCollection = RoomCollection = (function(_super) {
    __extends(RoomCollection, _super);

    function RoomCollection() {
      _ref2 = RoomCollection.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    RoomCollection.prototype.model = Room;

    return RoomCollection;

  })(Collection);

}).call(this);
