// Generated by CoffeeScript 1.6.3
(function() {
  var Mob, MobCollection, User, UserCollection, _ref, _ref1, _ref2,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('./mob'), Mob = _ref.Mob, MobCollection = _ref.MobCollection;

  exports.User = User = (function(_super) {
    __extends(User, _super);

    function User() {
      _ref1 = User.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    User.prototype.defaults = {
      age: 0,
      wasAtLocation: null,
      passwordHash: null
    };

    User.prototype.setPassword = function(password) {
      return this.set('password', "cleartext:" + password);
    };

    User.prototype.checkPassword = function(password) {
      var realpass;
      realpass = this.get('password');
      return ("cleartext:" + password) === realpass;
    };

    return User;

  })(Mob);

  exports.UserCollection = UserCollection = (function(_super) {
    __extends(UserCollection, _super);

    function UserCollection() {
      _ref2 = UserCollection.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    UserCollection.prototype.model = User;

    return UserCollection;

  })(MobCollection);

}).call(this);
