// Generated by CoffeeScript 1.6.3
(function() {
  var AreaCollection, Collection, Model, World, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('./'), Model = _ref.Model, Collection = _ref.Collection;

  AreaCollection = require('./area').AreaCollection;

  exports.World = World = (function(_super) {
    __extends(World, _super);

    function World() {
      _ref1 = World.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    World.prototype.initialize = function() {
      return this.areas = new AreaCollection();
    };

    return World;

  })(Model);

}).call(this);
