// Generated by CoffeeScript 1.6.3
(function() {
  var AreaCollection, Collection, CommandCollection, Model, UserCollection, World, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('./'), Model = _ref.Model, Collection = _ref.Collection;

  AreaCollection = require('./area').AreaCollection;

  CommandCollection = require('./command').CommandCollection;

  UserCollection = require('./user').UserCollection;

  exports.World = World = (function(_super) {
    __extends(World, _super);

    function World() {
      _ref1 = World.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    World.prototype.initialize = function() {
      this.areas = new AreaCollection(this);
      this.commands = new CommandCollection(this);
      this.users = new UserCollection(this);
      return this.world = this;
    };

    World.prototype.getStartRoom = function() {
      var area, room;
      area = this.world.areas.first();
      if (area == null) {
        throw new Error("Could not find any areas in the world");
      }
      room = area.rooms.first();
      if (room == null) {
        throw new Error("Could not find any rooms in " + (area.toString()));
      }
      return room;
    };

    return World;

  })(Model);

}).call(this);
