// Generated by CoffeeScript 1.6.3
(function() {
  var app, express;

  express = require('express');

  exports.app = app = express();

  app.set('view engine', 'jade');

  app.set('views', __dirname + '/../views');

  app.use(express.logger());

  app.get('/', function(req, res) {
    return res.redirect('/map');
  });

  app.get('/map', function(req, res) {
    var area, world;
    world = app.get('coffeekeep world');
    area = world.areas.get('school.are');
    return res.render('area', {
      area: area
    });
  });

  app.get('/map/:roomid', function(req, res) {
    var area, room, world;
    world = app.get('coffeekeep world');
    area = world.areas.get('school.are');
    room = area.rooms.get(req.params.roomid);
    return res.render('room', {
      room: room
    });
  });

  app.use(express.directory("" + __dirname + "/../public"));

  app.use(express["static"]("" + __dirname + "/../public"));

}).call(this);
