// Generated by CoffeeScript 1.6.3
(function() {
  var MudClientService, MudService, World, app, express, http, io, mudClientIO, mudClientService, mudService, server, terminal;

  terminal = require('term.js');

  io = require('socket.io');

  express = require('express');

  http = require('http');

  MudClientService = require('./terminal').MudClientService;

  MudService = require('./engine').MudService;

  World = require('./model/world').World;

  exports.app = app = express();

  exports.httpServer = server = http.createServer(app);

  app.set('view engine', 'jade');

  app.set('views', __dirname + '/../views');

  app.use(express.logger());

  app.use(terminal.middleware());

  app.get('/', function(req, res) {
    return res.redirect('/client');
  });

  app.get('/world', function(req, res) {
    var area, world;
    world = app.get('coffeekeep world');
    area = world.areas.first();
    return res.render('world', {
      world: world
    });
  });

  app.get('/world/:areaid', function(req, res) {
    var area, world;
    world = app.get('coffeekeep world');
    area = world.areas.get(req.params.areaid);
    return res.render('area', {
      area: area
    });
  });

  app.get('/world/:areaid/:roomid', function(req, res) {
    var area, room, world;
    world = app.get('coffeekeep world');
    area = world.areas.get(req.params.areaid);
    room = area.rooms.get(req.params.roomid);
    return res.render('room', {
      room: room
    });
  });

  app.get('/client', function(req, res) {
    return res.render('mudClient');
  });

  app.set('coffeekeep world', new World());

  mudService = new MudService(app.get('coffeekeep world'));

  mudClientIO = io.listen(server, {
    log: false
  }).of('/mudClient');

  mudClientService = new MudClientService(mudService, mudClientIO);

  app.use(express.directory("" + __dirname + "/../public"));

  app.use(express["static"]("" + __dirname + "/../public"));

}).call(this);
