// Generated by CoffeeScript 1.6.3
(function() {
  var Area, Room, World, app, httpServer, optimist, _ref;

  optimist = require('optimist');

  World = require('./model/world').World;

  Area = require('./model/area').Area;

  Room = require('./model/room').Room;

  _ref = require('./app'), app = _ref.app, httpServer = _ref.httpServer;

  exports.run = function() {
    var ROMReader, currentArea, rom, world;
    ROMReader = require('./readers/rom').ROMReader;
    world = new World();
    currentArea = null;
    rom = new ROMReader();
    rom.on('area', function(data) {
      currentArea = new Area(data);
      return world.areas.add(currentArea);
    });
    rom.on('room', function(data) {
      var room;
      room = new Room(data);
      room.area = currentArea;
      return currentArea.rooms.add(room);
    });
    rom.on('done', function() {
      var port, _ref1;
      app.set('coffeekeep world', world);
      port = (_ref1 = process.env.PORT) != null ? _ref1 : 5555;
      httpServer.listen(port);
      return console.log("Listening on port " + port);
    });
    return rom.read(optimist.argv._[0]);
  };

  if (module.parent == null) {
    exports.run();
  }

}).call(this);
