// Generated by CoffeeScript 1.6.3
(function() {
  var Area, Room, World, app, optimist;

  optimist = require('optimist');

  World = require('./model/world').World;

  Area = require('./model/area').Area;

  Room = require('./model/room').Room;

  app = require('./app').app;

  exports.run = function() {
    var ROMReader, currentArea, rom, world;
    ROMReader = require('./readers/rom').ROMReader;
    world = new World();
    currentArea = null;
    rom = new ROMReader();
    rom.on('area', function(data) {
      currentArea = new Area(data);
      return world.areas.add(currentArea);
    });
    rom.on('room', function(data) {
      var room;
      room = new Room(data);
      return currentArea.rooms.add(room);
    });
    rom.on('done', function() {
      var port, _ref;
      app.set('coffeekeep world', world);
      port = (_ref = process.env.PORT) != null ? _ref : 5555;
      app.listen(port);
      return console.log("Listening on port " + port);
    });
    return rom.read(__dirname + '/../areas/school.are');
  };

  if (module.parent == null) {
    exports.run();
  }

}).call(this);
