// Generated by CoffeeScript 1.6.3
(function() {
  var readline, rl;

  readline = require('readline');

  rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  rl.on('line', function(line) {
    var args, cmd, parts;
    if (line == null) {
      return;
    }
    if (line.length === 0) {
      return;
    }
    parts = line.split(' ');
    if (parts.length === 1) {
      cmd = parts[0];
      args = [];
    } else {
      cmd = parts[0];
      args = parts.slice(1);
    }
    return rl.write("You said " + cmd + " with args " + args);
  });

}).call(this);
