// Generated by CoffeeScript 1.6.3
(function() {
  var Area, Room, areaData;

  exports.rooms = {
    '100': {
      title: 'The Void',
      desc: 'You are in the middle of nothingness.',
      links: {
        south: {
          room: 200
        }
      }
    },
    '200': {
      title: 'Outside the Void',
      desc: 'Somehow you got outside the void.',
      links: {
        north: {
          room: 100
        }
      }
    }
  };

  areaData = {
    id: 'samplearea',
    title: 'Sample Area',
    rooms: exports.rooms
  };

  Area = (function() {
    function Area(data) {
      var id, room, rooms, _ref;
      this.data = data;
      _ref = this.data, this.id = _ref.id, this.title = _ref.title, this.description = _ref.description;
      rooms = this.data.rooms;
      console.log("Loading area " + this.id + " with " + rooms + " rooms...");
      this.rooms = {};
      for (id in rooms) {
        data = rooms[id];
        room = new Room(this, id, data);
        this.rooms[id] = room;
      }
    }

    Area.prototype.getRoom = function(id, callback) {
      if (this.rooms[id] == null) {
        callback(new Error("Room " + id + " does not exist"));
      }
      return callback(null, this.rooms[id]);
    };

    Area.prototype.getRoomList = function(callback) {
      var id, room, rooms, _ref;
      rooms = [];
      _ref = this.rooms;
      for (id in _ref) {
        room = _ref[id];
        rooms.push([id, room.title]);
      }
      return callback(null, rooms);
    };

    return Area;

  })();

  Room = (function() {
    function Room(area, id, data) {
      this.area = area;
      this.id = id;
      this.title = data.title, this.description = data.description, this.links = data.links;
      console.log("Loading room " + this.id + " in area " + this.area + "...");
    }

    return Room;

  })();

  exports.area = new Area(areaData);

}).call(this);
