// Generated by CoffeeScript 1.6.3
/*
Web-based Mud Client Service
*/


(function() {
  var EventEmitter, MudClientService, MudClientSession, io,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  io = require('socket.io');

  EventEmitter = require('events').EventEmitter;

  exports.MudClientSession = MudClientSession = (function(_super) {
    __extends(MudClientSession, _super);

    function MudClientSession(service, term) {
      var _this = this;
      this.service = service;
      this.term = term;
      this.mud = this.service.mudService.createSession(this);
      this.term.on('disconnect', function() {
        return _this.emit('close');
      });
      this.term.on('data', function(data) {
        return _this.emit('data', data);
      });
    }

    MudClientSession.prototype.write = function(data) {
      return this.term.emit('data', data);
    };

    MudClientSession.prototype.close = function() {
      this.term.emit('data', '\n\nConnection terminated by server');
      return this.term.disconnect();
    };

    return MudClientSession;

  })(EventEmitter);

  exports.MudClientService = MudClientService = (function() {
    function MudClientService(mudService, termService) {
      var _this = this;
      this.mudService = mudService;
      this.termService = termService;
      this.termService.on('connection', function(socket) {
        return _this.registerSession(socket);
      });
      this.sessions = {};
    }

    MudClientService.prototype.registerSession = function(socket) {
      var session;
      session = new MudClientSession(this, socket);
      return this.sessions[socket.id] = session;
    };

    MudClientService.prototype.unregisterSession = function(session) {
      return delete this.sessions[session.term.id];
    };

    return MudClientService;

  })();

}).call(this);
