// Generated by CoffeeScript 1.6.3
(function() {
  var _;

  _ = require('underscore');

  exports.splitFull = function(text, sep, maxsplit) {
    var out, parts, splits;
    if (maxsplit == null) {
      maxsplit = -1;
    }
    if (sep == null) {
      sep = /(\s+)/;
    }
    parts = text.split(sep);
    if (maxsplit === -1) {
      if (_.isRegExp(sep)) {
        out = [];
        while (parts.length > 0) {
          out.push(parts.shift());
          parts.shift();
        }
        return out;
      } else {
        return parts;
      }
    }
    out = [];
    splits = 0;
    while (parts.length > 0 && splits <= maxsplits) {
      out.push(parts.shift());
      if (_.isRegExp(sep)) {
        parts.shift();
      }
    }
    if (sep instanceof RegExp) {
      parts = parts.join('');
    } else {
      parts = parts.join(sep);
    }
    out.push(parts);
    return out;
  };

}).call(this);
