// Generated by CoffeeScript 1.6.3
(function() {
  exports.splitFull = function(text, sep, maxsplit) {
    var out, parts, splits;
    if (maxsplit == null) {
      maxsplit = -1;
    }
    if (sep == null) {
      sep = /(\s+)/;
    }
    parts = text.split(sep);
    if (maxsplit === -1) {
      return parts;
    }
    out = [];
    splits = 0;
    while (parts.length > 0 && splits <= maxsplits) {
      out.push(parts.shift());
      if (sep instanceof RegExp) {
        parts.shift();
      }
    }
    if (sep instanceof RegExp) {
      parts = parts.join('');
    } else {
      parts = parts.join(sep);
    }
    out.push(parts);
    return out;
  };

}).call(this);
