// Generated by CoffeeScript 1.6.3
/*
Base class for reading Area files from different MUD formats. The base
class reads from a JSON file to serve as an example. Uses the event system.

Events: `area`, `room`
*/


(function() {
  var AreaReader, events, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  events = require('events');

  AreaReader = (function(_super) {
    __extends(AreaReader, _super);

    function AreaReader() {
      _ref = AreaReader.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AreaReader.prototype.read = function(file) {
      var area, areaFile, id, room, _ref1;
      areaFile = require(file);
      console.log("AreaReader: " + (JSON.stringify(areaFile)));
      if (areaFile == null) {
        return;
      }
      area = {
        id: areaFile.id,
        title: areaFile.title,
        description: areaFile.description
      };
      this.emit('area', area);
      if (areaFile.rooms != null) {
        _ref1 = areaFile.rooms;
        for (id in _ref1) {
          room = _ref1[id];
          room.id = id;
          this.emit('room', room);
        }
      }
      return this.emit('done');
    };

    return AreaReader;

  })(events.EventEmitter);

  exports.AreaReader = AreaReader;

}).call(this);
